// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/meu_coelho_mq.proto

package MeuCoelhoMQProto;

public interface ChannelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MeuCoelhoMQProto.Channel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.MeuCoelhoMQProto.Tipo tipo = 2;</code>
   * @return The enum numeric value on the wire for tipo.
   */
  int getTipoValue();
  /**
   * <code>.MeuCoelhoMQProto.Tipo tipo = 2;</code>
   * @return The tipo.
   */
  MeuCoelhoMQProto.Tipo getTipo();
}
