// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/meu_coelho_mq.proto

package MeuCoelhoMQProto;

public interface CredentialsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MeuCoelhoMQProto.Credentials)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
