// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/meu_coelho_mq.proto

package MeuCoelhoMQProto;

public final class MeuCoelhoMQProto {
  private MeuCoelhoMQProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MeuCoelhoMQProto_Credentials_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MeuCoelhoMQProto_Credentials_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MeuCoelhoMQProto_Subscriber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MeuCoelhoMQProto_Subscriber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MeuCoelhoMQProto_Channel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MeuCoelhoMQProto_Channel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MeuCoelhoMQProto_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MeuCoelhoMQProto_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MeuCoelhoMQProto_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MeuCoelhoMQProto_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032protos/meu_coelho_mq.proto\022\020MeuCoelhoM" +
      "QProto\"+\n\013Credentials\022\n\n\002id\030\001 \001(\t\022\020\n\010pas" +
      "sword\030\002 \001(\t\"Q\n\nSubscriber\0222\n\013credentials" +
      "\030\001 \001(\0132\035.MeuCoelhoMQProto.Credentials\022\017\n" +
      "\007channel\030\002 \001(\t\"=\n\007Channel\022\014\n\004name\030\001 \001(\t\022" +
      "$\n\004tipo\030\002 \001(\0162\026.MeuCoelhoMQProto.Tipo\"(\n" +
      "\007Message\022\014\n\004data\030\001 \001(\t\022\017\n\007channel\030\002 \001(\t\"" +
      "\034\n\010Response\022\020\n\010response\030\001 \001(\t*!\n\004Tipo\022\013\n" +
      "\007SIMPLES\020\000\022\014\n\010MULTIPLO\020\0012\200\005\n\013MeuCoelhoMQ" +
      "\022H\n\rCreateChannel\022\031.MeuCoelhoMQProto.Cha" +
      "nnel\032\032.MeuCoelhoMQProto.Response\"\000\022H\n\rDe" +
      "leteChannel\022\031.MeuCoelhoMQProto.Channel\032\032" +
      ".MeuCoelhoMQProto.Response\"\000\022I\n\014ListChan" +
      "nels\022\032.MeuCoelhoMQProto.Response\032\031.MeuCo" +
      "elhoMQProto.Channel\"\0000\001\022I\n\016PublishMessag" +
      "e\022\031.MeuCoelhoMQProto.Message\032\032.MeuCoelho" +
      "MQProto.Response\"\000\022G\n\010Register\022\035.MeuCoel" +
      "hoMQProto.Credentials\032\032.MeuCoelhoMQProto" +
      ".Response\"\000\022P\n\022SubscribeToChannel\022\034.MeuC" +
      "oelhoMQProto.Subscriber\032\032.MeuCoelhoMQPro" +
      "to.Response\"\000\022U\n\027ConsultNumberOfMessages" +
      "\022\034.MeuCoelhoMQProto.Subscriber\032\032.MeuCoel" +
      "hoMQProto.Response\"\000\022U\n\025GetMessageFromCh" +
      "annel\022\034.MeuCoelhoMQProto.Subscriber\032\032.Me" +
      "uCoelhoMQProto.Response\"\0000\001B,\n\020MeuCoelho" +
      "MQProtoB\020MeuCoelhoMQProtoP\001\242\002\003RTGb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MeuCoelhoMQProto_Credentials_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MeuCoelhoMQProto_Credentials_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MeuCoelhoMQProto_Credentials_descriptor,
        new java.lang.String[] { "Id", "Password", });
    internal_static_MeuCoelhoMQProto_Subscriber_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MeuCoelhoMQProto_Subscriber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MeuCoelhoMQProto_Subscriber_descriptor,
        new java.lang.String[] { "Credentials", "Channel", });
    internal_static_MeuCoelhoMQProto_Channel_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MeuCoelhoMQProto_Channel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MeuCoelhoMQProto_Channel_descriptor,
        new java.lang.String[] { "Name", "Tipo", });
    internal_static_MeuCoelhoMQProto_Message_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_MeuCoelhoMQProto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MeuCoelhoMQProto_Message_descriptor,
        new java.lang.String[] { "Data", "Channel", });
    internal_static_MeuCoelhoMQProto_Response_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_MeuCoelhoMQProto_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MeuCoelhoMQProto_Response_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
