// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/meu_coelho_mq.proto

package MeuCoelhoMQProto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MeuCoelhoMQProto.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   * @return The response.
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   * @return The bytes for response.
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
