// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/meu_coelho_mq.proto

package MeuCoelhoMQProto;

/**
 * Protobuf type {@code MeuCoelhoMQProto.Subscriber}
 */
public final class Subscriber extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MeuCoelhoMQProto.Subscriber)
    SubscriberOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Subscriber.newBuilder() to construct.
  private Subscriber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Subscriber() {
    channel_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Subscriber();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Subscriber(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            MeuCoelhoMQProto.Credentials.Builder subBuilder = null;
            if (credentials_ != null) {
              subBuilder = credentials_.toBuilder();
            }
            credentials_ = input.readMessage(MeuCoelhoMQProto.Credentials.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(credentials_);
              credentials_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            channel_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MeuCoelhoMQProto.MeuCoelhoMQProto.internal_static_MeuCoelhoMQProto_Subscriber_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MeuCoelhoMQProto.MeuCoelhoMQProto.internal_static_MeuCoelhoMQProto_Subscriber_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MeuCoelhoMQProto.Subscriber.class, MeuCoelhoMQProto.Subscriber.Builder.class);
  }

  public static final int CREDENTIALS_FIELD_NUMBER = 1;
  private MeuCoelhoMQProto.Credentials credentials_;
  /**
   * <code>.MeuCoelhoMQProto.Credentials credentials = 1;</code>
   * @return Whether the credentials field is set.
   */
  @java.lang.Override
  public boolean hasCredentials() {
    return credentials_ != null;
  }
  /**
   * <code>.MeuCoelhoMQProto.Credentials credentials = 1;</code>
   * @return The credentials.
   */
  @java.lang.Override
  public MeuCoelhoMQProto.Credentials getCredentials() {
    return credentials_ == null ? MeuCoelhoMQProto.Credentials.getDefaultInstance() : credentials_;
  }
  /**
   * <code>.MeuCoelhoMQProto.Credentials credentials = 1;</code>
   */
  @java.lang.Override
  public MeuCoelhoMQProto.CredentialsOrBuilder getCredentialsOrBuilder() {
    return getCredentials();
  }

  public static final int CHANNEL_FIELD_NUMBER = 2;
  private volatile java.lang.Object channel_;
  /**
   * <code>string channel = 2;</code>
   * @return The channel.
   */
  @java.lang.Override
  public java.lang.String getChannel() {
    java.lang.Object ref = channel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      channel_ = s;
      return s;
    }
  }
  /**
   * <code>string channel = 2;</code>
   * @return The bytes for channel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChannelBytes() {
    java.lang.Object ref = channel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      channel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (credentials_ != null) {
      output.writeMessage(1, getCredentials());
    }
    if (!getChannelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, channel_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (credentials_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCredentials());
    }
    if (!getChannelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, channel_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MeuCoelhoMQProto.Subscriber)) {
      return super.equals(obj);
    }
    MeuCoelhoMQProto.Subscriber other = (MeuCoelhoMQProto.Subscriber) obj;

    if (hasCredentials() != other.hasCredentials()) return false;
    if (hasCredentials()) {
      if (!getCredentials()
          .equals(other.getCredentials())) return false;
    }
    if (!getChannel()
        .equals(other.getChannel())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCredentials()) {
      hash = (37 * hash) + CREDENTIALS_FIELD_NUMBER;
      hash = (53 * hash) + getCredentials().hashCode();
    }
    hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
    hash = (53 * hash) + getChannel().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MeuCoelhoMQProto.Subscriber parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MeuCoelhoMQProto.Subscriber parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MeuCoelhoMQProto.Subscriber parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MeuCoelhoMQProto.Subscriber parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MeuCoelhoMQProto.Subscriber parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MeuCoelhoMQProto.Subscriber parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MeuCoelhoMQProto.Subscriber parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MeuCoelhoMQProto.Subscriber parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MeuCoelhoMQProto.Subscriber parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MeuCoelhoMQProto.Subscriber parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MeuCoelhoMQProto.Subscriber parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MeuCoelhoMQProto.Subscriber parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MeuCoelhoMQProto.Subscriber prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MeuCoelhoMQProto.Subscriber}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MeuCoelhoMQProto.Subscriber)
      MeuCoelhoMQProto.SubscriberOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MeuCoelhoMQProto.MeuCoelhoMQProto.internal_static_MeuCoelhoMQProto_Subscriber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MeuCoelhoMQProto.MeuCoelhoMQProto.internal_static_MeuCoelhoMQProto_Subscriber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MeuCoelhoMQProto.Subscriber.class, MeuCoelhoMQProto.Subscriber.Builder.class);
    }

    // Construct using MeuCoelhoMQProto.Subscriber.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (credentialsBuilder_ == null) {
        credentials_ = null;
      } else {
        credentials_ = null;
        credentialsBuilder_ = null;
      }
      channel_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MeuCoelhoMQProto.MeuCoelhoMQProto.internal_static_MeuCoelhoMQProto_Subscriber_descriptor;
    }

    @java.lang.Override
    public MeuCoelhoMQProto.Subscriber getDefaultInstanceForType() {
      return MeuCoelhoMQProto.Subscriber.getDefaultInstance();
    }

    @java.lang.Override
    public MeuCoelhoMQProto.Subscriber build() {
      MeuCoelhoMQProto.Subscriber result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public MeuCoelhoMQProto.Subscriber buildPartial() {
      MeuCoelhoMQProto.Subscriber result = new MeuCoelhoMQProto.Subscriber(this);
      if (credentialsBuilder_ == null) {
        result.credentials_ = credentials_;
      } else {
        result.credentials_ = credentialsBuilder_.build();
      }
      result.channel_ = channel_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MeuCoelhoMQProto.Subscriber) {
        return mergeFrom((MeuCoelhoMQProto.Subscriber)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MeuCoelhoMQProto.Subscriber other) {
      if (other == MeuCoelhoMQProto.Subscriber.getDefaultInstance()) return this;
      if (other.hasCredentials()) {
        mergeCredentials(other.getCredentials());
      }
      if (!other.getChannel().isEmpty()) {
        channel_ = other.channel_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MeuCoelhoMQProto.Subscriber parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MeuCoelhoMQProto.Subscriber) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private MeuCoelhoMQProto.Credentials credentials_;
    private com.google.protobuf.SingleFieldBuilderV3<
        MeuCoelhoMQProto.Credentials, MeuCoelhoMQProto.Credentials.Builder, MeuCoelhoMQProto.CredentialsOrBuilder> credentialsBuilder_;
    /**
     * <code>.MeuCoelhoMQProto.Credentials credentials = 1;</code>
     * @return Whether the credentials field is set.
     */
    public boolean hasCredentials() {
      return credentialsBuilder_ != null || credentials_ != null;
    }
    /**
     * <code>.MeuCoelhoMQProto.Credentials credentials = 1;</code>
     * @return The credentials.
     */
    public MeuCoelhoMQProto.Credentials getCredentials() {
      if (credentialsBuilder_ == null) {
        return credentials_ == null ? MeuCoelhoMQProto.Credentials.getDefaultInstance() : credentials_;
      } else {
        return credentialsBuilder_.getMessage();
      }
    }
    /**
     * <code>.MeuCoelhoMQProto.Credentials credentials = 1;</code>
     */
    public Builder setCredentials(MeuCoelhoMQProto.Credentials value) {
      if (credentialsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        credentials_ = value;
        onChanged();
      } else {
        credentialsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.MeuCoelhoMQProto.Credentials credentials = 1;</code>
     */
    public Builder setCredentials(
        MeuCoelhoMQProto.Credentials.Builder builderForValue) {
      if (credentialsBuilder_ == null) {
        credentials_ = builderForValue.build();
        onChanged();
      } else {
        credentialsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.MeuCoelhoMQProto.Credentials credentials = 1;</code>
     */
    public Builder mergeCredentials(MeuCoelhoMQProto.Credentials value) {
      if (credentialsBuilder_ == null) {
        if (credentials_ != null) {
          credentials_ =
            MeuCoelhoMQProto.Credentials.newBuilder(credentials_).mergeFrom(value).buildPartial();
        } else {
          credentials_ = value;
        }
        onChanged();
      } else {
        credentialsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.MeuCoelhoMQProto.Credentials credentials = 1;</code>
     */
    public Builder clearCredentials() {
      if (credentialsBuilder_ == null) {
        credentials_ = null;
        onChanged();
      } else {
        credentials_ = null;
        credentialsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.MeuCoelhoMQProto.Credentials credentials = 1;</code>
     */
    public MeuCoelhoMQProto.Credentials.Builder getCredentialsBuilder() {
      
      onChanged();
      return getCredentialsFieldBuilder().getBuilder();
    }
    /**
     * <code>.MeuCoelhoMQProto.Credentials credentials = 1;</code>
     */
    public MeuCoelhoMQProto.CredentialsOrBuilder getCredentialsOrBuilder() {
      if (credentialsBuilder_ != null) {
        return credentialsBuilder_.getMessageOrBuilder();
      } else {
        return credentials_ == null ?
            MeuCoelhoMQProto.Credentials.getDefaultInstance() : credentials_;
      }
    }
    /**
     * <code>.MeuCoelhoMQProto.Credentials credentials = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        MeuCoelhoMQProto.Credentials, MeuCoelhoMQProto.Credentials.Builder, MeuCoelhoMQProto.CredentialsOrBuilder> 
        getCredentialsFieldBuilder() {
      if (credentialsBuilder_ == null) {
        credentialsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            MeuCoelhoMQProto.Credentials, MeuCoelhoMQProto.Credentials.Builder, MeuCoelhoMQProto.CredentialsOrBuilder>(
                getCredentials(),
                getParentForChildren(),
                isClean());
        credentials_ = null;
      }
      return credentialsBuilder_;
    }

    private java.lang.Object channel_ = "";
    /**
     * <code>string channel = 2;</code>
     * @return The channel.
     */
    public java.lang.String getChannel() {
      java.lang.Object ref = channel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string channel = 2;</code>
     * @return The bytes for channel.
     */
    public com.google.protobuf.ByteString
        getChannelBytes() {
      java.lang.Object ref = channel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string channel = 2;</code>
     * @param value The channel to set.
     * @return This builder for chaining.
     */
    public Builder setChannel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      channel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string channel = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChannel() {
      
      channel_ = getDefaultInstance().getChannel();
      onChanged();
      return this;
    }
    /**
     * <code>string channel = 2;</code>
     * @param value The bytes for channel to set.
     * @return This builder for chaining.
     */
    public Builder setChannelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      channel_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MeuCoelhoMQProto.Subscriber)
  }

  // @@protoc_insertion_point(class_scope:MeuCoelhoMQProto.Subscriber)
  private static final MeuCoelhoMQProto.Subscriber DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MeuCoelhoMQProto.Subscriber();
  }

  public static MeuCoelhoMQProto.Subscriber getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Subscriber>
      PARSER = new com.google.protobuf.AbstractParser<Subscriber>() {
    @java.lang.Override
    public Subscriber parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Subscriber(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Subscriber> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Subscriber> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public MeuCoelhoMQProto.Subscriber getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

