// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/meu_coelho_mq.proto

package MeuCoelhoMQProto;

public interface SubscriberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MeuCoelhoMQProto.Subscriber)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MeuCoelhoMQProto.Credentials credentials = 1;</code>
   * @return Whether the credentials field is set.
   */
  boolean hasCredentials();
  /**
   * <code>.MeuCoelhoMQProto.Credentials credentials = 1;</code>
   * @return The credentials.
   */
  MeuCoelhoMQProto.Credentials getCredentials();
  /**
   * <code>.MeuCoelhoMQProto.Credentials credentials = 1;</code>
   */
  MeuCoelhoMQProto.CredentialsOrBuilder getCredentialsOrBuilder();

  /**
   * <code>string channel = 2;</code>
   * @return The channel.
   */
  java.lang.String getChannel();
  /**
   * <code>string channel = 2;</code>
   * @return The bytes for channel.
   */
  com.google.protobuf.ByteString
      getChannelBytes();
}
