// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/meu_coelho_mq.proto

package MeuCoelhoMQProto;

/**
 * Protobuf enum {@code MeuCoelhoMQProto.Tipo}
 */
public enum Tipo
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SIMPLES = 0;</code>
   */
  SIMPLES(0),
  /**
   * <code>MULTIPLO = 1;</code>
   */
  MULTIPLO(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SIMPLES = 0;</code>
   */
  public static final int SIMPLES_VALUE = 0;
  /**
   * <code>MULTIPLO = 1;</code>
   */
  public static final int MULTIPLO_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Tipo valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Tipo forNumber(int value) {
    switch (value) {
      case 0: return SIMPLES;
      case 1: return MULTIPLO;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Tipo>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Tipo> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Tipo>() {
          public Tipo findValueByNumber(int number) {
            return Tipo.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return MeuCoelhoMQProto.MeuCoelhoMQProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final Tipo[] VALUES = values();

  public static Tipo valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Tipo(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:MeuCoelhoMQProto.Tipo)
}

