# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/meu_coelho_mq.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotos/meu_coelho_mq.proto\x12\x10MeuCoelhoMQProto\"+\n\x0b\x43redentials\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"Q\n\nSubscriber\x12\x32\n\x0b\x63redentials\x18\x01 \x01(\x0b\x32\x1d.MeuCoelhoMQProto.Credentials\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\"=\n\x07\x43hannel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x04tipo\x18\x02 \x01(\x0e\x32\x16.MeuCoelhoMQProto.Tipo\"(\n\x07Message\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\",\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05*!\n\x04Tipo\x12\x0b\n\x07SIMPLES\x10\x00\x12\x0c\n\x08MULTIPLO\x10\x01\x32\x80\x05\n\x0bMeuCoelhoMQ\x12H\n\rCreateChannel\x12\x19.MeuCoelhoMQProto.Channel\x1a\x1a.MeuCoelhoMQProto.Response\"\x00\x12H\n\rDeleteChannel\x12\x19.MeuCoelhoMQProto.Channel\x1a\x1a.MeuCoelhoMQProto.Response\"\x00\x12I\n\x0cListChannels\x12\x1a.MeuCoelhoMQProto.Response\x1a\x19.MeuCoelhoMQProto.Channel\"\x00\x30\x01\x12I\n\x0ePublishMessage\x12\x19.MeuCoelhoMQProto.Message\x1a\x1a.MeuCoelhoMQProto.Response\"\x00\x12G\n\x08Register\x12\x1d.MeuCoelhoMQProto.Credentials\x1a\x1a.MeuCoelhoMQProto.Response\"\x00\x12P\n\x12SubscribeToChannel\x12\x1c.MeuCoelhoMQProto.Subscriber\x1a\x1a.MeuCoelhoMQProto.Response\"\x00\x12U\n\x17\x43onsultNumberOfMessages\x12\x1c.MeuCoelhoMQProto.Subscriber\x1a\x1a.MeuCoelhoMQProto.Response\"\x00\x12U\n\x15GetMessageFromChannel\x12\x1c.MeuCoelhoMQProto.Subscriber\x1a\x1a.MeuCoelhoMQProto.Response\"\x00\x30\x01\x42,\n\x10MeuCoelhoMQProtoB\x10MeuCoelhoMQProtoP\x01\xa2\x02\x03RTGb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.meu_coelho_mq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020MeuCoelhoMQProtoB\020MeuCoelhoMQProtoP\001\242\002\003RTG'
  _globals['_TIPO']._serialized_start=327
  _globals['_TIPO']._serialized_end=360
  _globals['_CREDENTIALS']._serialized_start=48
  _globals['_CREDENTIALS']._serialized_end=91
  _globals['_SUBSCRIBER']._serialized_start=93
  _globals['_SUBSCRIBER']._serialized_end=174
  _globals['_CHANNEL']._serialized_start=176
  _globals['_CHANNEL']._serialized_end=237
  _globals['_MESSAGE']._serialized_start=239
  _globals['_MESSAGE']._serialized_end=279
  _globals['_RESPONSE']._serialized_start=281
  _globals['_RESPONSE']._serialized_end=325
  _globals['_MEUCOELHOMQ']._serialized_start=363
  _globals['_MEUCOELHOMQ']._serialized_end=1003
# @@protoc_insertion_point(module_scope)
