# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/meu_qoelho_mq.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotos/meu_qoelho_mq.proto\x12\x0bmeuqoelhomq\"+\n\x0b\x43redentials\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"L\n\nSubscriber\x12-\n\x0b\x63redentials\x18\x01 \x01(\x0b\x32\x18.meuqoelhomq.Credentials\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\"9\n\x08\x43hannels\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1f\n\x04tipo\x18\x02 \x01(\x0e\x32\x11.meuqoelhomq.Tipo\"(\n\x07Message\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\",\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05*!\n\x04Tipo\x12\x0b\n\x07SIMPLES\x10\x00\x12\x0c\n\x08MULTIPLO\x10\x01\x32\xb3\x04\n\x0bMeuQoelhoMQ\x12?\n\rCreateChannel\x12\x15.meuqoelhomq.Channels\x1a\x15.meuqoelhomq.Response\"\x00\x12?\n\rDeleteChannel\x12\x15.meuqoelhomq.Channels\x1a\x15.meuqoelhomq.Response\"\x00\x12@\n\x0cListChannels\x12\x15.meuqoelhomq.Response\x1a\x15.meuqoelhomq.Channels\"\x00\x30\x01\x12?\n\x0ePublishMessage\x12\x14.meuqoelhomq.Message\x1a\x15.meuqoelhomq.Response\"\x00\x12=\n\x08Register\x12\x18.meuqoelhomq.Credentials\x1a\x15.meuqoelhomq.Response\"\x00\x12\x46\n\x12SubscribeToChannel\x12\x17.meuqoelhomq.Subscriber\x1a\x15.meuqoelhomq.Response\"\x00\x12K\n\x17\x43onsultNumberOfMessages\x12\x17.meuqoelhomq.Subscriber\x1a\x15.meuqoelhomq.Response\"\x00\x12K\n\x15GetMessageFromChannel\x12\x17.meuqoelhomq.Subscriber\x1a\x15.meuqoelhomq.Response\"\x00\x30\x01\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.meu_qoelho_mq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_TIPO']._serialized_start=313
  _globals['_TIPO']._serialized_end=346
  _globals['_CREDENTIALS']._serialized_start=43
  _globals['_CREDENTIALS']._serialized_end=86
  _globals['_SUBSCRIBER']._serialized_start=88
  _globals['_SUBSCRIBER']._serialized_end=164
  _globals['_CHANNELS']._serialized_start=166
  _globals['_CHANNELS']._serialized_end=223
  _globals['_MESSAGE']._serialized_start=225
  _globals['_MESSAGE']._serialized_end=265
  _globals['_RESPONSE']._serialized_start=267
  _globals['_RESPONSE']._serialized_end=311
  _globals['_MEUQOELHOMQ']._serialized_start=349
  _globals['_MEUQOELHOMQ']._serialized_end=912
# @@protoc_insertion_point(module_scope)
