# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/meu_qoelho_mq.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotos/meu_qoelho_mq.proto\x12\x10MeuQoelhoMQProto\"+\n\x0b\x43redentials\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"Q\n\nSubscriber\x12\x32\n\x0b\x63redentials\x18\x01 \x01(\x0b\x32\x1d.MeuQoelhoMQProto.Credentials\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\">\n\x08\x43hannels\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x04tipo\x18\x02 \x01(\x0e\x32\x16.MeuQoelhoMQProto.Tipo\"(\n\x07Message\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\",\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05*!\n\x04Tipo\x12\x0b\n\x07SIMPLES\x10\x00\x12\x0c\n\x08MULTIPLO\x10\x01\x32\x83\x05\n\x0bMeuQoelhoMQ\x12I\n\rCreateChannel\x12\x1a.MeuQoelhoMQProto.Channels\x1a\x1a.MeuQoelhoMQProto.Response\"\x00\x12I\n\rDeleteChannel\x12\x1a.MeuQoelhoMQProto.Channels\x1a\x1a.MeuQoelhoMQProto.Response\"\x00\x12J\n\x0cListChannels\x12\x1a.MeuQoelhoMQProto.Response\x1a\x1a.MeuQoelhoMQProto.Channels\"\x00\x30\x01\x12I\n\x0ePublishMessage\x12\x19.MeuQoelhoMQProto.Message\x1a\x1a.MeuQoelhoMQProto.Response\"\x00\x12G\n\x08Register\x12\x1d.MeuQoelhoMQProto.Credentials\x1a\x1a.MeuQoelhoMQProto.Response\"\x00\x12P\n\x12SubscribeToChannel\x12\x1c.MeuQoelhoMQProto.Subscriber\x1a\x1a.MeuQoelhoMQProto.Response\"\x00\x12U\n\x17\x43onsultNumberOfMessages\x12\x1c.MeuQoelhoMQProto.Subscriber\x1a\x1a.MeuQoelhoMQProto.Response\"\x00\x12U\n\x15GetMessageFromChannel\x12\x1c.MeuQoelhoMQProto.Subscriber\x1a\x1a.MeuQoelhoMQProto.Response\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.meu_qoelho_mq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIPO']._serialized_start=328
  _globals['_TIPO']._serialized_end=361
  _globals['_CREDENTIALS']._serialized_start=48
  _globals['_CREDENTIALS']._serialized_end=91
  _globals['_SUBSCRIBER']._serialized_start=93
  _globals['_SUBSCRIBER']._serialized_end=174
  _globals['_CHANNELS']._serialized_start=176
  _globals['_CHANNELS']._serialized_end=238
  _globals['_MESSAGE']._serialized_start=240
  _globals['_MESSAGE']._serialized_end=280
  _globals['_RESPONSE']._serialized_start=282
  _globals['_RESPONSE']._serialized_end=326
  _globals['_MEUQOELHOMQ']._serialized_start=364
  _globals['_MEUQOELHOMQ']._serialized_end=1007
# @@protoc_insertion_point(module_scope)
